// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCjIrt9R3ChZ2vAimcURg843nGCzydAWSU',
    appId: '1:208866748817:web:00a6c702fbd9b0f7edd230',
    messagingSenderId: '208866748817',
    projectId: 'blackoffer-9f348',
    authDomain: 'blackoffer-9f348.firebaseapp.com',
    storageBucket: 'blackoffer-9f348.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBMbvVgHuokH7INnwh5hkmPAm0D8cqbdqs',
    appId: '1:208866748817:android:ef2ca080bf7a926fedd230',
    messagingSenderId: '208866748817',
    projectId: 'blackoffer-9f348',
    storageBucket: 'blackoffer-9f348.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6N8kKSSK27vyhQoExtfHSVewecd-7Rxo',
    appId: '1:208866748817:ios:a31c3c9fc5916148edd230',
    messagingSenderId: '208866748817',
    projectId: 'blackoffer-9f348',
    storageBucket: 'blackoffer-9f348.appspot.com',
    iosBundleId: 'com.example.healtify',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB6N8kKSSK27vyhQoExtfHSVewecd-7Rxo',
    appId: '1:208866748817:ios:a31c3c9fc5916148edd230',
    messagingSenderId: '208866748817',
    projectId: 'blackoffer-9f348',
    storageBucket: 'blackoffer-9f348.appspot.com',
    iosBundleId: 'com.example.healtify',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCjIrt9R3ChZ2vAimcURg843nGCzydAWSU',
    appId: '1:208866748817:web:1743e2d8506214cbedd230',
    messagingSenderId: '208866748817',
    projectId: 'blackoffer-9f348',
    authDomain: 'blackoffer-9f348.firebaseapp.com',
    storageBucket: 'blackoffer-9f348.appspot.com',
  );

}